/* Generated by CMake — system feature detection */
#ifndef CONFIG_H
#define CONFIG_H
#define HAVE_STRLCPY
#define HAVE_GAI_STRERROR
#define HAVE_NETINET_IN_H
#define HAVE_NETINET_IP_H
#define HAVE_DECL_TIOCSRS485 0
#define HAVE_DECL_TIOCM_RTS 0

#endif /* CONFIG_H */
