set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

# ── 项目名称 ────────────────────────────────────
set(ACLASS_PROJECT_NAME "AClassDemo_${ARCH}" CACHE STRING "Project name for output naming")

# ── 库链接模式 ────────────────────────────────────
set(ACLASS_LIB_MODE "STATIC" CACHE STRING "Library mode: SHARED, STATIC or OBJECT")
set_property(CACHE ACLASS_LIB_MODE PROPERTY STRINGS SHARED STATIC OBJECT)

if(NOT ACLASS_LIB_MODE STREQUAL "SHARED")
    set(BUILD_SHARED_LIBS OFF)
else()
    set(BUILD_SHARED_LIBS ON)
endif()

# ── 输出目录 ──────────────────────────────────────
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

set(CMAKE_SKIP_BUILD_RPATH FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
set(CMAKE_INSTALL_RPATH "\$ORIGIN/../lib")
