# cmake/toolchain-armv7.cmake
# armv7 交叉编译 — 从 .project.local.config 读取 COMPILE_PATH / SYSROOT_PATH

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(DEFINED COMPILE_PATH)
    set(CMAKE_C_COMPILER "${COMPILE_PATH}/arm-linux-gnueabihf-gcc")
endif()

if(DEFINED COMPILE_PATH)
    set(CMAKE_SYSROOT "${SYSROOT_PATH}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)